begin;
do $$
declare broker uuid; admin_user uuid; broker_name text; lid uuid; other_lid uuid; sid uuid; e jsonb; tid uuid; count_before int; denied boolean;
begin
 select id,coalesce(corretor_ref,nome) into broker,broker_name from public.usuarios where perfil='corretor' limit 1;
 select id into admin_user from public.usuarios where perfil='admin' limit 1;
 insert into public.leads(nome,corretor,status) values('__CRM_SEQUENCE_TEST_OTHER__','__OTHER__','followup') returning id into other_lid;
 perform set_config('request.jwt.claim.sub',admin_user::text,true);
 execute 'set local role authenticated';
 insert into public.followup_sequencias(nome,ativa,created_by,passos) values('__AYRA_SEQUENCE_TEST__',true,admin_user,'[{"titulo":"Enviar vídeo","dias":1,"orientacao":"Apresentação"},{"titulo":"Retorno","dias":2,"orientacao":"Perguntar interesse"}]') returning id into sid;
 perform set_config('request.jwt.claim.sub',broker::text,true);
 insert into public.leads(nome,corretor,status) values('__CRM_SEQUENCE_TEST__',broker_name,'atendimento') returning id into lid;
 denied:=false;
 begin perform public.crm_followup_start(other_lid,sid,now()+interval '1 day');exception when others then denied:=true;end;
 assert denied,'Broker accessed another lead';
 denied:=false;
 begin insert into public.followup_sequencias(nome,ativa,created_by,passos) values('__BROKER_DENIED__',true,broker,'[]');exception when insufficient_privilege then denied:=true;end;
 assert denied,'Broker created a sequence';
 e:=public.crm_followup_start(lid,sid,now()+interval '1 day');
 assert (select status='followup' from public.leads where id=lid),'Start did not move stage';
 perform public.crm_followup_start(lid,sid,now()+interval '1 day');
 assert (select count(*)=1 from public.tarefas where followup_lead_id=lid),'Duplicate start created tasks';
 select id into tid from public.tarefas where followup_lead_id=lid and not concluida;
 perform public.crm_followup_complete(tid,'Não respondeu','message');
 perform public.crm_followup_complete(tid,'Não respondeu','message');
 assert (select count(*)=2 from public.tarefas where followup_lead_id=lid),'Duplicate completion advanced twice';
 assert (select etapa_atual=1 from public.followup_leads where lead_id=lid),'Next step missing';
 select id into tid from public.tarefas where followup_lead_id=lid and not concluida;
 assert (select data_hora between now()+interval '47 hours' and now()+interval '49 hours' from public.tarefas where id=tid),'Wrong interval';
 perform public.crm_followup_complete(tid,'Pediu mais tempo','call','Data combinada',now()+interval '5 days');
 assert (select not concluida and data_hora=now()+interval '5 days' from public.tarefas where id=tid),'Reschedule failed';
 perform public.crm_followup_state(lid,'pausado');
 assert (select count(*)=0 from public.tarefas where followup_lead_id=lid and not concluida),'Pause left pending tasks';
 perform public.crm_followup_state(lid,'ativo',now()+interval '3 days');
 assert (select count(*)=1 from public.tarefas where followup_lead_id=lid and not concluida),'Resume task missing';
 denied:=false;
 begin perform public.crm_followup_complete(tid,'Sem interesse','message','');exception when others then denied:=true;end;
 assert denied,'Discard accepted without reason';
 perform public.crm_followup_complete(tid,'Respondeu','message','Quer conhecer','now'::timestamptz,'proposta');
 assert (select status='proposta' from public.leads where id=lid),'Response stage failed';
 assert (select estado='pausado' from public.followup_leads where lead_id=lid),'Response did not pause';
 perform public.crm_followup_start(lid,sid,now()+interval '1 day');
 select id into tid from public.tarefas where followup_lead_id=lid and not concluida;
 perform public.crm_followup_complete(tid,'Sem interesse','call','Não deseja comprar');
 assert (select status='perdido' from public.leads where id=lid),'Discard stage failed';
 assert (select estado='concluido' from public.followup_leads where lead_id=lid),'Discard did not end';
 perform public.crm_followup_start(lid,sid,now()+interval '1 day');
 select id into tid from public.tarefas where followup_lead_id=lid and not concluida;
 perform public.crm_followup_complete(tid,'Não respondeu','message');
 select id into tid from public.tarefas where followup_lead_id=lid and not concluida;
 perform public.crm_followup_complete(tid,'Não respondeu','message');
 assert (select estado='concluido' and etapa_atual=2 from public.followup_leads where lead_id=lid),'End not concluded';
 assert (select status='followup' from public.leads where id=lid),'End discarded automatically';
 perform public.crm_followup_start(lid,sid,now()+interval '1 day');
 update public.leads set status='atendimento' where id=lid;
 assert (select estado='pausado' from public.followup_leads where lead_id=lid),'Manual stage change did not pause';
 assert (select count(*)=0 from public.tarefas where followup_lead_id=lid and not concluida),'Manual stage change left tasks';
 execute 'reset role';
end $$;
rollback;
select 'Passed: creation, ownership, duplicate protection, next interval, reschedule, pause/resume, response, discard reason, exhaustion, manual stage change. Test data rolled back.' as verification;
